project_name: space-prompt
before:
release:
  github:
    owner: thetechnick
    name: go-space-prompt
  prerelease: true
builds:
  - &build-cli
    id: space-prompt
    binary: space-prompt
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
      - arm
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/space-prompt/main.go
archives:
  - id: space-prompt
    builds:
      - space-prompt
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
